
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(['windows_app.py'],
             pathex=['F:\trae_projects\Subnet_Planner'],
             binaries=[],
             datas=[('translations.json', '.'), ('Subnet_Planner.ico', '.'), ('icon.ico', '.'), ('Picture', 'Picture')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[
                 'tkinter.test',
                 'unittest',
                 'pytest',
                 'doctest',
                 'numpy',
                 'scipy',
                 'matplotlib',
                 'pandas',
                 'PIL._tkinter_finder',
                 'PIL.ImageQt',
                 'PIL.TiffImagePlugin',
                 'PIL.JpegImagePlugin',
                 'PIL.PngImagePlugin',
                 'PIL.GifImagePlugin',
                 'xmlrpc',
                 'urllib3',
                 'requests',
                 'cryptography',
                 'cffi',
                 'pycparser',
                 'pyOpenSSL',
                 'winreg',
                 '_winreg',
                 'win32api',
                 'win32con',
                 'win32gui',
                 'win32process',
                 'win32security',
                 'win32service',
                 'win32serviceutil',
                 'win32event',
                 'win32evtlog',
                 'win32evtlogutil',
                 'win32clipboard',
                 'win32com',
                 'pythoncom',
                 'win32timezone',
                 'winsound',
                 'msvcrt',
                 'fcntl',
                 'pwd',
                 'grp',
                 'spwd',
                 'resource',
                 'imp',
                 'modulefinder',
                 'sitecustomize',
                 'usercustomize',
                 'idlelib',
                 'pydoc',
                 'test',
                 'lib2to3',
                 'debug',
                 'code',
                 'codeop',
                 'readline',
                 'rlcompleter',
             ],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(pyz,
        a.scripts,
        a.binaries,
        a.zipfiles,
        a.datas,
        [],
        name='SubnetPlannerV2.6.5',
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=False,
        upx_exclude=[],
        runtime_tmpdir=None,
        console=False,
        icon='Subnet_Planner.ico',
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        uac_admin=False,
        uac_uiaccess=False,
        onefile=True)
